echo on
echo  

echo beign to run python scripts....
python ID_Generator.py
python Msg_Generator.py


echo delete old files....
@rem del ..\..\server\GameServer\MMOServer\Common\src\main\java\com\mrd\game\message\*.java
@rem del ..\..\client\Assets\Scripts\Logic\NetModule\AutoGenerated\*.cs
@rem del ..\clientCplus\NetModule\AutoGenerated\*.cc
@rem del ..\clientCplus\NetModule\AutoGenerated\*.h



echo begin to copy Message class...
@rem copy /y .\protofiles\*.cs ..\..\client\Assets\Scripts\Logic\NetModule\AutoGenerated\*.cs
@rem copy /y .\protofiles\com\mrd\game\message\*.java ..\..\server\GameServer\MMOServer\Common\src\main\java\com\mrd\game\message\*.java

@rem  copy /y .\protofiles\*.cc ..\clientCplus\NetModule\AutoGenerated\*.cc
@rem  copy /y .\protofiles\*.h ..\clientCplus\NetModule\AutoGenerated\*.h
@rem  copy /y .\*.h ..\clientCplus\NetModule\AutoGenerated\*.h


echo begin to copy Id class...
@rem copy /y .\*.cs ..\..\client\Assets\Scripts\Logic\NetModule\AutoGenerated\*.cs
@rem copy /y .\*.java ..\..\server\GameServer\MMOServer\Common\src\main\java\com\mrd\game\message\*.java

@rem echo begin del generated temp files...
@rem del *.cs
@rem del *.java
@rem del *.h

@rem rd /s/q .\protofiles\vine
@rem del .\protofiles\*.cs
@rem
@rem del .\protofiles\*.cc
@rem del .\protofiles\*.h

rd /s/q ProtocolCommon


pause